### ISSUE TITLE
IEEE checklist

### ISSUE THREAD

**Issue by ericprud** [shexSpec/spec#61]
1. [ ] Labeling: Is the draft properly labeled? For example, IEEE P1234/D1, Jan 20XX, Draft Standard for…
2. [ ] Copyright: Does the first page include the copyright statement? Do all pages include the copyright footer with the current year?
3. [ ] Introduction: Has an introduction been prepared, giving the history of the standard and a description of its purpose?
4. [ ] Overall completeness and quality: Is the draft complete, legible, and free of comments and tracked changes? Are pages, figures, and tables numbered consecutively?
5. [ ] Figures: Are figures legible? *Avoid the use of color alone to convey meaning.
6. [ ] Normative references: Are the references cited in normative text so that it is clear that the reference is required to implement the standard? Non-normative references shall be placed in an informative annex entitled “Bibliography.” Other considerations include the following:
   * [ ] The reference is publicly available at reasonable cost
   * [ ] If draft standards are included, they shall be marked as drafts (draft number and date)
   * [ ] If non-standard documents are included, the citation shall include the date of publication
   * [ ] In-text citations shall match the normative reference in Clause 2
   * [ ] References to specific parts of other documents shall include the date/edition
   * [ ] The normatively referenced material in the document meets the restrictions on commercial terms (see 6.2.2 of the IEEE SA Standards Board Operations Manual)
7. [ ] Cross-referencing: Are all figures, tables, equations, and annexes called out in text?
8. [ ] Definitions: Are the definitions properly constructed? Are sources cited in parentheses after the definitions? Did you use terms and definitions from the IEEE Standards Dictionary Online instead of creating new definitions or slightly modifying existing definitions?
9. [ ] Verb usage: Are the verb choices (shall, should, or may) generally appropriate for the type of document (standard, recommended practice, or guide)?
10. [ ] Permissions/copyright: Does the draft contain borrowed material (e.g., text, tables, figures) from previously published material (other than IEEE)? If so, letters of permission must be sent to STDS-PERM-LTRS@ieee.org before the start of the IEEE SA ballot. Sample IEEE Permission Form Request and Response Letters for working groups are available for download.
11. [ ] Units: Metric units shall be provided, and inch-pound data may be included parenthetically to the metric unit. Exceptions are allowed per IEEE SASB Implementation Plan.
12. [ ] Mathematical expressions: Are variables in italics, while constants set in roman? Are variables defined in an equation variable list following each equation?
13. [ ] Amendments or Corrigenda: If the draft is an amendment or corrigendum, are instructions on changes to the existing standard clearly shown and explained? If not, please simplify the instructions.
